default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: esx_development

test:
  <<: *default
  database: esx_test

production:
  <<: *default
  database: esx_production
  username: esx
  password: <%= ENV["ESX_DATABASE_PASSWORD"] %>